# Generated by Django 2.2.1 on 2019-05-16 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EventCenter', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='event_id',
            new_name='event',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='channel_id',
            new_name='channel',
        ),
        migrations.RenameField(
            model_name='like',
            old_name='event_id',
            new_name='event',
        ),
        migrations.RenameField(
            model_name='like',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='participation',
            old_name='event_id',
            new_name='event',
        ),
        migrations.RenameField(
            model_name='participation',
            old_name='user_id',
            new_name='user',
        ),
    ]
