# Generated by Django 2.2.1 on 2019-05-16 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EventCenter', '0002_auto_20190516_1501'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='channel',
            table='channel_tab',
        ),
        migrations.AlterModelTable(
            name='comment',
            table='comment_tab',
        ),
        migrations.AlterModelTable(
            name='event',
            table='event_tab',
        ),
        migrations.AlterModelTable(
            name='like',
            table='like_tab',
        ),
        migrations.AlterModelTable(
            name='participation',
            table='participation_tab',
        ),
    ]
