# Generated by Django 2.2.1 on 2019-05-16 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventCenter', '0004_auto_20190516_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.TextField(default='default', max_length=2000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='image_url',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
