# Generated by Django 2.2.1 on 2019-05-16 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EventCenter', '0005_auto_20190516_1741'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='date',
            new_name='timestamp',
        ),
    ]
