# Generated by Django 2.2.1 on 2019-05-16 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventCenter', '0006_auto_20190516_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='image_url',
            field=models.URLField(),
        ),
    ]
