# Generated by Django 2.2.1 on 2019-05-30 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventCenter', '0010_auto_20190522_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='timestamp',
            field=models.BigIntegerField(),
        ),
    ]
